package main

import (
	"strconv"
	"time"

	. "github.com/xyproto/browserspeak"
	"github.com/xyproto/web"
	//"github.com/hoisie/mustache"
)

type ArchPageContents struct {
	generatedCSSurl          string
	extraCSSurl              string
	faviconurl               string
	bgImageURL               string
	stretchBackground        bool
	title                    string
	subtitle                 string
	links                    []string
	contentTitle             string
	contentHTML              string
	searchButtonText         string
	searchURL                string
	footerText               string
	backgroundTextureURL     string
	darkBackgroundTextureURL string
	footerTextColor          string
	footerColor              string
	userState                *UserState
	roundedLook              bool
}

type APCgen (func(userState *UserState) *ArchPageContents)

// TODO: Use mustache for easy replacement of "login" or "register" on the menu
func archbuilder(apc *ArchPageContents) *Page {
	page := NewHTML5Page(apc.title + " " + apc.subtitle)

	page.LinkToCSS(apc.generatedCSSurl)
	page.LinkToCSS(apc.extraCSSurl)
	page.LinkToFavicon(apc.faviconurl)

	AddHeader(page)
	AddBodyStyle(page, apc.bgImageURL, apc.stretchBackground)
	AddTopBox(page, apc.title, apc.subtitle, apc.searchURL, apc.searchButtonText, apc.backgroundTextureURL, apc.roundedLook)

	// TODO:
	// Use something dynamic to add or remove /login and /register depending on the login status
	// The login status can be fetched over AJAX or REST or something.

	AddMenuBox(page, apc.links, apc.darkBackgroundTextureURL)
	AddContent(page, apc.contentTitle, apc.contentHTML)
	AddFooter(page, apc.footerText, apc.footerTextColor, apc.footerColor)

	return page
}

// Make an html and css page available, plus a search handler (they are special)
func (apc *ArchPageContents) Pub(url string, search WebHandle) {
	archpage := archbuilder(apc)
	web.Get(url, HTML(archpage))
	web.Get(apc.generatedCSSurl, CSS(archpage))
	web.Get(apc.extraCSSurl, GenerateExtraCSS(apc.stretchBackground))
	web.Get(apc.searchURL+"(.*)", search)
}

// Wrap a lonely string in an entire webpage
func (apc *ArchPageContents) Surround(s string) (string, string) {
	apc.contentHTML = s
	archpage := archbuilder(apc)
	return archpage.GetXML(true), archpage.GetCSS()
}

// Creates a handle from a string function
func (apc *ArchPageContents) GetHandle(fn StringFunction) WebHandle {
	return func(ctx *web.Context, val string) string {
		html, css := apc.Surround(fn(val))
		web.Get(apc.generatedCSSurl, css)
		return html
	}
}

// Wraps the looks of an ArchPageContents + a string function together to a web.go handle
func wrapHandle(apcgen APCgen, sf StringFunction, userState *UserState) WebHandle {
	apc := apcgen(userState)
	return apc.GetHandle(sf)
}

// Creeates a page based on ArchPageContens generated by apcgen
// Publishes the HTML and CSS at the given URL
func pub(url string, apcgen APCgen, userState *UserState) {
	apc := apcgen(userState)
	apc.Pub(url, apc.GenerateSearchHandle())
}

// Subpages

func CountAPC(userState *UserState) *ArchPageContents {
	apc := BaseAPC(userState)
	apc.contentTitle = "Counting"
	apc.contentHTML = "1 2 3"
	return apc
}

func HiAPC(userState *UserState) *ArchPageContents {
	apc := BaseAPC(userState)
	apc.contentTitle = "Overview"
	//apc.contentHTML = `This site is currently under construction.<br />You may wish to visit the <a href="https://bbs.archlinux.org/viewtopic.php?id=4998">Arch Linux Forum</a> in the mean time.<br /><br /><i>- Alexander Rødseth &lt;rodseth / gmail&gt;</i>`
	//apc.contentTitle = "YOLO narwhal"
	apc.contentHTML = `
<p>Locavore Austin fanny pack pickled.  Marfa hoodie pitchfork american apparel, flexitarian YOLO pickled keytar twee cred craft beer seitan authentic raw denim kogi.  Selvage mixtape blog, pickled cosby sweater williamsburg skateboard brooklyn lo-fi twee.  Blue bottle echo park kale chips, selvage fap skateboard swag chambray tousled.  Street art etsy four loko fap, iphone carles cliche banh mi fashion axe PBR authentic leggings.  Narwhal mumblecore street art tumblr.  Messenger bag vice art party, next level aesthetic church-key tumblr direct trade  typewriter street art.</p><p>Messenger bag blue bottle VHS before they sold out.  Artisan pickled swag, VHS meggings jean shorts blog tonx salvia cosby sweater mumblecore aesthetic literally narwhal.  Brunch tofu gluten-free disrupt blog occupy.  Austin bicycle rights sartorial narwhal, butcher trust fund cred.  Neutra kale chips letterpress literally, williamsburg kogi brunch bicycle rights.  Williamsburg craft beer brunch quinoa, forage YOLO swag put a bird on it four loko mixtape banksy.  Tumblr semiotics yr fixie.</p><p>Iphone banksy wolf squid wayfarers, VHS photo booth banh mi fap.  Tonx flexitarian vinyl scenester terry richardson squid synth deep v.  VHS tousled godard, cardigan american apparel lo-fi flannel.  Vice church-key cliche, hashtag banh mi direct trade  skateboard.  Sriracha meh pitchfork, wayfarers helvetica leggings try-hard viral YOLO lo-fi fingerstache synth ennui next level ugh.  Wayfarers organic american apparel fingerstache craft beer bicycle rights, beard keffiyeh banksy four loko butcher hashtag mumblecore banjo wes anderson.  Williamsburg next level deep v pickled typewriter kogi.</p><p>Meggings gastropub flexitarian, before they sold out DIY wes anderson cred authentic artisan dreamcatcher aesthetic ennui food truck.  Fanny pack selvage synth vegan pug.  YOLO shoreditch pitchfork, letterpress whatever put a bird on it truffaut mumblecore flannel terry richardson irony cray master cleanse ethnic gluten-free.  Fap banksy blog pickled meh ethnic food truck +1, vice leggings retro quinoa.  Small batch vice pop-up mustache.  +1 ethnic echo park semiotics letterpress raw denim.  Keytar photo booth wes anderson, freegan before they sold out skateboard seitan brooklyn.</p><p>Wes anderson high life banksy messenger bag art party plaid disrupt tattooed, next level swag viral raw denim.  Cliche meggings terry richardson cray.  Next level 3 wolf moon retro marfa.  Pork belly authentic banjo, iphone lomo williamsburg letterpress cosby sweater Austin typewriter quinoa skateboard hoodie.  Plaid kale chips godard farm-to-table.  Fashion axe mixtape freegan, pop-up chambray ugh etsy YOLO jean shorts dreamcatcher meggings.  Banh mi letterpress tousled, skateboard stumptown high life vegan fap typewriter shoreditch 8-bit lo-fi master cleanse selfies bespoke.</p>
`
	return apc
}

func HelloAPC(userState *UserState) *ArchPageContents {
	apc := BaseAPC(userState)
	apc.contentTitle = "This is it"
	return apc
}

// Generate a search handle. This is done in order to be able to modify the apc
func (apc *ArchPageContents) GenerateSearchHandle() WebHandle {
	return func(ctx *web.Context, val string) string {
		q, found := ctx.Params["q"]
		searchText := UserInput(q)
		var html, css string
		if found {
			apc.contentTitle = "Search results"
			content := "Search: " + string(searchText)
			nl := tagString("br")
			content += nl + nl
			content += "No results found"
			html, css = apc.Surround(content)
		} else {
			apc.contentTitle = "Error"
			html, css = apc.Surround("Invalid parameters")
		}
		web.Get(apc.generatedCSSurl, css)
		return html
	}
}

// The main page / default settings
func BaseAPC(userState *UserState) *ArchPageContents {
	var apc ArchPageContents
	apc.generatedCSSurl = "/css/style.css"
	apc.extraCSSurl = "/css/extra.css"
	apc.faviconurl = "/favicon.ico"
	//apc.bgImageURL = "/img/longbg.png"
	//apc.bgImageURL = "http://home.online.no/~hakrist/Elg%20i%20solnedgang%201024.JPG"
	//apc.bgImageURL = "http://upload.wikimedia.org/wikipedia/commons/1/1f/Theodor_Kittelsen,_Soria_Moria.jpg"
	//apc.bgImageURL = "http://www.dks-hordaland.no/media/bilde/elgisolnedgang.jpg"
	//apc.bgImageURL = "/img/rough.png"
	//apc.bgImageURL = "/img/donutbg.png"
	//apc.bgImageURL = "/img/donutbg_light.jpg"
	//apc.bgImageURL = "/img/boxes_cartoon2.png"
	//apc.bgImageURL = "/img/boxes_softglow.png"
	//apc.bgImageURL = "/img/space_predator.png"
	//apc.bgImageURL = "/img/space_predator_tile.png"
	//apc.bgImageURL = "/img/centerimage.png"
	//apc.bgImageURL = "/img/underwater.png"
	//apc.bgImageURL = "/img/underwater.jpg"
	//apc.bgImageURL = "/img/norway.jpg"
	//apc.bgImageURL = "/img/norway2.jpg"
	apc.bgImageURL = "/img/norway3.jpg"
	apc.stretchBackground = true
	apc.title = "Arch Linux"
	apc.subtitle = "no"
	apc.links = []string{"Overview:/", "Mirrors:/mirrors", "Login:/login", "Register:/register", "Hello:/hello/world", "Count:/counting", "Feedback:/feedback"}
	apc.contentTitle = "Hi"
	apc.contentHTML = "Hi there!"
	apc.searchButtonText = "Search"
	apc.searchURL = "/search"
	// http://wptheming.wpengine.netdna-cdn.com/wp-content/uploads/2010/04/gray-texture.jpg
	apc.backgroundTextureURL = "/img/gray.jpg"
	// http://turbo.designwoop.com/uploads/2012/03/16_free_subtle_textures_subtle_dark_vertical.jpg
	apc.darkBackgroundTextureURL = "/img/darkgray.jpg"
	apc.footerColor = "black"
	apc.footerTextColor = "#303040"
	y := time.Now().Year()
	//apc.footerText = "Alexander Rødseth &lt;rodseth@gmail.com&gt;, " + strconv.Itoa(y)
	apc.footerText = "Alexander Rødseth, " + strconv.Itoa(y)
	apc.userState = userState
	apc.roundedLook = false
	return &apc
}

// Routing for the archlinux.no webpage
func ServeArchlinuxNo(userState *UserState) {
	faviconFilename := "generated/img/favicon.ico"
	genFavicon(faviconFilename)

	pub("/", HiAPC, userState)
	web.Get("/hello/(.*)", wrapHandle(HelloAPC, helloSF, userState))
	pub("/counting", CountAPC, userState)

	pub("/mirrors", HelloAPC, userState)
	pub("/login", HelloAPC, userState)
	pub("/register", HelloAPC, userState)
	pub("/feedback", HelloAPC, userState)

	Publish("/robots.txt", "static/various/robots.txt")
	Publish("/sitemap_index.xml", "static/various/sitemap_index.xml")

	// Images
	//Publish("/img/rough.png", "static/img/rough.png")
	//Publish("/img/longbg.png", "static/img/longbg.png")
	Publish("/img/donutbg.png", "static/img/donutbg.png")
	//Publish("/img/donutbg_light.jpg", "static/img/donutbg_light.jpg")
	//Publish("/img/boxes_cartoon2.png", "static/img/boxes_cartoon2.png")
	//Publish("/img/boxes_softglow.png", "static/img/boxes_softglow.png")
	//Publish("/img/felix_predator2.jpg", "static/img/felix_predator2.jpg")
	//Publish("/img/space_predator.png", "static/img/space_predator.png")
	//Publish("/img/centerimage.png", "static/img/centerimage.png")
	//Publish("/img/underwater.png", "static/img/underwater.png")
	Publish("/img/underwater.jpg", "static/img/underwater.jpg")
	//Publish("/img/norway.jpg", "static/img/norway.jpg")
	//Publish("/img/norway2.jpg", "static/img/norway2.jpg")
	Publish("/img/norway3.jpg", "static/img/norway3.jpg")
	Publish("/img/gray.jpg", "static/img/gray.jpg")
	Publish("/img/darkgray.jpg", "static/img/darkgray.jpg")

	Publish("/favicon.ico", faviconFilename)

	//pubTemplate("/yes", templateGenerator(), templateContent{a:2})
}
